#[repr(C)]
#[derive(Debug)]
pub enum ErrnoCode {
    ESUCCESS,
    EPERM,
    ENOENT,
    ESRCH,
    EINTR,
    EIO,
    ENXIO,
    E2BIG,
    ENOEXEC,
    EBADF,
    ECHILD,
    EAGAIN,
    ENOMEM,
    EACCES,
    EFAULT,
    ENOTBLK,
    EBUSY,
    EEXIST,
    EXDEV,
    ENODEV,
    ENOTDIR,
    EISDIR,
    EINVAL,
    ENFILE,
    EMFILE,
    ENOTTY,
    ETXTBSY,
    EFBIG,
    ENOSPC,
    ESPIPE,
    EROFS,
    EMLINK,
    EPIPE,
    ERANGE,
    ENAMETOOLONG,
    ELOOP,
    EOVERFLOW,
    EOPNOTSUPP,
    ENOSYS,
    ENOTIMPL,
    EAFNOSUPPORT,
    ENOTSOCK,
    EADDRINUSE,
    ENOTEMPTY,
    EDOM,
    ECONNREFUSED,
    EHOSTDOWN,
    EADDRNOTAVAIL,
    EISCONN,
    ECONNABORTED,
    EALREADY,
    ECONNRESET,
    EDESTADDRREQ,
    EHOSTUNREACH,
    EILSEQ,
    EMSGSIZE,
    ENETDOWN,
    ENETUNREACH,
    ENETRESET,
    ENOBUFS,
    ENOLCK,
    ENOMSG,
    ENOPROTOOPT,
    ENOTCONN,
    ESHUTDOWN,
    ETOOMANYREFS,
    ESOCKTNOSUPPORT,
    EPROTONOSUPPORT,
    EDEADLK,
    ETIMEDOUT,
    EPROTOTYPE,
    EINPROGRESS,
    ENOTHREAD,
    EPROTO,
    ENOTSUP,
    EPFNOSUPPORT,
    EDIRINTOSELF,
    EDQUOT,
    ENOTRECOVERABLE,
    ECANCELED,
    EPROMISEVIOLATION,
    ESTALE,
    EMAXERRNO,
}

impl ErrnoCode {
    pub fn msg(&self) -> &'static str {
	match self {
	    &ErrnoCode::ESUCCESS => "Success (not an error)",
	    &ErrnoCode::EPERM => "Operation not permitted",
	    &ErrnoCode::ENOENT => "No such file or directory",
	    &ErrnoCode::ESRCH => "No such process",
	    &ErrnoCode::EINTR => "Interrupted syscall",
	    &ErrnoCode::EIO => "I/O error",
	    &ErrnoCode::ENXIO => "No such device or address",
	    &ErrnoCode::E2BIG => "Argument list too long",
	    &ErrnoCode::ENOEXEC => "Exec format error",
	    &ErrnoCode::EBADF => "Bad fd number",
	    &ErrnoCode::ECHILD => "No child processes",
	    &ErrnoCode::EAGAIN => "Try again",
	    &ErrnoCode::ENOMEM => "Out of memory",
	    &ErrnoCode::EACCES => "Permission denied",
	    &ErrnoCode::EFAULT => "Bad address",
	    &ErrnoCode::ENOTBLK => "Block device required",
	    &ErrnoCode::EBUSY => "Device or resource busy",
	    &ErrnoCode::EEXIST => "File already exists",
	    &ErrnoCode::EXDEV => "Cross-device link",
	    &ErrnoCode::ENODEV => "No such device",
	    &ErrnoCode::ENOTDIR => "Not a directory",
	    &ErrnoCode::EISDIR => "Is a directory",
	    &ErrnoCode::EINVAL => "Invalid argument",
	    &ErrnoCode::ENFILE => "File table overflow",
	    &ErrnoCode::EMFILE => "Too many open files",
	    &ErrnoCode::ENOTTY => "Not a TTY",
	    &ErrnoCode::ETXTBSY => "Text file busy",
	    &ErrnoCode::EFBIG => "File too large",
	    &ErrnoCode::ENOSPC => "No space left on device",
	    &ErrnoCode::ESPIPE => "Illegal seek",
	    &ErrnoCode::EROFS => "Read-only filesystem",
	    &ErrnoCode::EMLINK => "Too many links",
	    &ErrnoCode::EPIPE => "Broken pipe",
	    &ErrnoCode::ERANGE => "Range error",
	    &ErrnoCode::ENAMETOOLONG => "Name too long",
	    &ErrnoCode::ELOOP => "Too many symlinks",
	    &ErrnoCode::EOVERFLOW => "Overflow",
	    &ErrnoCode::EOPNOTSUPP => "Operation not supported",
	    &ErrnoCode::ENOSYS => "No such syscall",
	    &ErrnoCode::ENOTIMPL => "Not implemented",
	    &ErrnoCode::EAFNOSUPPORT => "Address family not supported",
	    &ErrnoCode::ENOTSOCK => "Not a socket",
	    &ErrnoCode::EADDRINUSE => "Address in use",
	    &ErrnoCode::ENOTEMPTY => "Directory not empty",
	    &ErrnoCode::EDOM => "Math argument out of domain",
	    &ErrnoCode::ECONNREFUSED => "Connection refused",
	    &ErrnoCode::EHOSTDOWN => "Host is down",
	    &ErrnoCode::EADDRNOTAVAIL => "Address not available",
	    &ErrnoCode::EISCONN => "Already connected",
	    &ErrnoCode::ECONNABORTED => "Connection aborted",
	    &ErrnoCode::EALREADY => "Connection already in progress",
	    &ErrnoCode::ECONNRESET => "Connection reset",
	    &ErrnoCode::EDESTADDRREQ => "Destination address required",
	    &ErrnoCode::EHOSTUNREACH => "Host unreachable",
	    &ErrnoCode::EILSEQ => "Illegal byte sequence",
	    &ErrnoCode::EMSGSIZE => "Message size",
	    &ErrnoCode::ENETDOWN => "Network down",
	    &ErrnoCode::ENETUNREACH => "Network unreachable",
	    &ErrnoCode::ENETRESET => "Network reset",
	    &ErrnoCode::ENOBUFS => "No buffer space",
	    &ErrnoCode::ENOLCK => "No lock available",
	    &ErrnoCode::ENOMSG => "No message",
	    &ErrnoCode::ENOPROTOOPT => "No protocol option",
	    &ErrnoCode::ENOTCONN => "Not connected",
	    &ErrnoCode::ESHUTDOWN => "Transport endpoint has shutdown",
	    &ErrnoCode::ETOOMANYREFS => "Too many references",
	    &ErrnoCode::ESOCKTNOSUPPORT => "Socket type not supported",
	    &ErrnoCode::EPROTONOSUPPORT => "Protocol not supported",
	    &ErrnoCode::EDEADLK => "Resource deadlock would occur",
	    &ErrnoCode::ETIMEDOUT => "Timed out",
	    &ErrnoCode::EPROTOTYPE => "Wrong protocol type",
	    &ErrnoCode::EINPROGRESS => "Operation in progress",
	    &ErrnoCode::ENOTHREAD => "No such thread",
	    &ErrnoCode::EPROTO => "Protocol error",
	    &ErrnoCode::ENOTSUP => "Not supported",
	    &ErrnoCode::EPFNOSUPPORT => "Protocol family not supported",
	    &ErrnoCode::EDIRINTOSELF => "Cannot make directory a subdirectory of itself",
	    &ErrnoCode::EDQUOT => "Quota exceeded",
	    &ErrnoCode::ENOTRECOVERABLE => "State not recoverable",
	    &ErrnoCode::ECANCELED => "Operation cancelled",
	    &ErrnoCode::EPROMISEVIOLATION => "The process has a promise violation",
	    &ErrnoCode::ESTALE => "Stale network file handle",
	    &ErrnoCode::EMAXERRNO => "The highest errno",
	}
    }
}
